# -*- coding: utf-8 -*-
"""Project_RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xXCDxOA17pTdv2qEx8NA6DGJ16lSbH6X

<center><font size=10>Project NLP - Healthcare</center></font>
<center><font size=6>Retrieval-Augmented Generation (RAG)</center></font>

![link text](https://d2ms8rpfqc4h24.cloudfront.net/leveraging_ai_powered_virtual_health_assistants_for_enhanced_patient_education_13dabc22ce.jpg)

## **Problem Definition**

The healthcare industry is rapidly evolving, and professionals face increasing challenges in managing vast volumes of medical data while delivering accurate and timely diagnoses. Quick access to comprehensive, reliable, and up-to-date medical knowledge is critical for improving patient outcomes and ensuring informed decision-making in a fast-paced environment.

Healthcare professionals often encounter information overload, struggling to sift through extensive research and data to create accurate diagnoses and treatment plans. This challenge is amplified by the need for efficiency, particularly in emergencies, where time-sensitive decisions are vital. Furthermore, access to trusted, current medical information from renowned manuals and research papers is essential for maintaining high standards of care.

To address these challenges, healthcare centers can focus on integrating systems that streamline access to medical knowledge, provide tools to support quick decision-making and enhance efficiency. Leveraging centralized knowledge platforms and ensuring healthcare providers have continuous access to reliable resources can significantly improve patient care and operational effectiveness.

## Objective

As an AI specialist, your task is to develop a RAG-based AI solution using renowned medical manuals to address healthcare challenges. The objective is to understand information overload, apply AI techniques to streamline decision-making, analyze its impact on diagnostics and patient outcomes, evaluate its potential to standardize care practices, and create a functional prototype demonstrating its feasibility and effectiveness.

## Questions to Answer

*  What is the protocol for managing sepsis in a critical care unit?
* What are the common symptoms of appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?
* What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?
* What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?
* What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?

## **Installing and Importing the Necessary Libraries**
"""

# Installation for GPU llama-cpp-python
!CMAKE_ARGS="-DLLAMA_CUBLAS=off" FORCE_CMAKE=1 pip install llama-cpp-python==0.2.28  --force-reinstall --upgrade --no-cache-dir -q 2>/dev/null
!pip uninstall -y numpy pandas chromadb
!pip install -q numpy==1.26.0 pandas==2.1.4 pypdf==4.0.1 langchain==0.1.1 langchain-community==0.0.13 chromadb==0.4.18 sentence-transformers==2.3.1 huggingface_hub==0.23.2 tiktoken

import json
import tiktoken

import pandas as pd
import numpy as np

# Function to download the model from the Hugging Face model hub
from huggingface_hub import hf_hub_download

# Importing the Llama class from the llama_cpp module
from llama_cpp import Llama

from langchain.text_splitter import RecursiveCharacterTextSplitter

from langchain_community.document_loaders import PyPDFDirectoryLoader, PyPDFLoader
from langchain_community.embeddings.sentence_transformer import (
    SentenceTransformerEmbeddings
)
from langchain_community.vectorstores import Chroma

import chromadb

from google.colab import userdata, drive

import warnings
warnings.filterwarnings('ignore')

"""## **Downloading Model and Loading**"""

# Defining the Hugging Face repository and model version for Mistral-7B fine-tuned for instruction-following
model_name_or_path = 'TheBloke/Mistral-7B-Instruct-v0.2-GGUF'

# Specifying the file name for the quantized Mistral-7B model in GGUF format (Q6_K for optimal performance)
model_basename = 'mistral-7b-instruct-v0.2.Q6_K.gguf'

# Downloading the specified model file from Hugging Face Hub and store its local path
model_path = hf_hub_download(
    repo_id=model_name_or_path, #The Hugging Face repository containing the model
    filename=model_basename  # The specific model file to download (in GGUF format)
)
#The GGUF format is used because it provides memory-efficient storage and faster inference while maintaining compatibility across different hardware platforms.

llm = Llama(
    model_path=model_path, #Path to the GGUF model file
    n_ctx=2300, #Sets the context window to 2300 tokens (how much text the model can "see" at once)
    n_gpu_layers=38, #Loads 38 model layers onto GPU for faster inference (set to 0 for CPU-only)
    n_batch=512, #Number of tokens processed at once
    #verbose=False # Disable verbose output to avoid the fileno error
)

"""## **Model Performance check with Basic Parameters**"""

def response(query, max_tokens=512, temperature=0, top_p=0.95, top_k=50):
    # Sends the query prompt to the LLM with specified generation parameters
    model_output = llm(
        prompt=query, #The user's input question or prompt sent to the LLM
        max_tokens=max_tokens, #Maximum number of tokens to generate
        temperature=temperature, #Controls randomness
        top_p=top_p, #picks from top tokens that make up top_p of total probability
        top_k=top_k #considers only the top_k most likely tokens
    )
    # Extracting and returning only the text part of the response
    return model_output['choices'][0]['text'].strip()

print(response('What is the protocol for managing sepsis in a critical care unit?'))

print(response('What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?'))

print(response('What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?'))

print(response('What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?'))

print(response('What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?'))

"""### Obervation

*   High Medical Appropriateness: The model consistently generates answers that are medically accurate and appropriate for the stated conditions (brain injury, hair loss, sepsis, fractured leg), validating its factual reliability in this domain.

* Comprehensive Content: Responses are generally detailed and cover a broad spectrum of necessary information, demonstrating strong knowledge acquisition (e.g., listing multiple treatments or protocol steps).

* Excellent Structure and Readability: Answers are presented in a clear, organized format, frequently using numbered lists or distinct sections, which makes the complex medical information easy for a user to read and follow.

* Strong Contextual Relevance: The model remains focused on the query's core topic, generating precise and relevant information without drifting off-topic.

*   Generic Content Depth: While answers are appropriate, they often feel high-level or like general guidelines (e.g., standard protocol steps). They lack the nuance and situational depth that might be required for specific clinical scenarios.

*   Need for Contextual Specificity: The model defaults to useful but basic responses. The information provided is generally applicable rather than highly tailored, implying a need to fine-tune the prompt to demand greater contextual precision.

Lets leverage prompt engineering to enhance the quality of our responses.

## **Q&A with Prompt Engineering to define parameters**

Lets change the LLM parameter and check the effectiveness of the response

* temp (Temperature): A scalar value that controls the randomness (or "creativity") of the model's output by scaling the probability distribution of the next token.
* top_p (Nucleus Sampling): A dynamic sampling filter that restricts the choice of the next token to the smallest set of highest-probability tokens whose cumulative probability exceeds the threshold $p$.
* top_k: A static sampling filter that restricts the model's choice to only the $K$ most likely tokens at each step.
* max_tokens: A hard limit that defines the maximum number of tokens the model is allowed to generate in its response.

### Response function
"""

def generate_llama_response(query, temperature, top_p, top_k, max_tokens, instruction="Answer the following question clearly and concisely."):

    # Create system message with instructions for the model
    system_message = f"[INST]<<SYS>>\n{instruction}\n<</SYS>>[/INST]"

    # Construct the final prompt using the user's query and system message
    prompt = f"{system_message} {query}"

    # Generate a response using the LLaMA model
    response = llm(
        prompt=prompt,
        max_tokens=max_tokens,
        temperature=temperature,
        top_p=top_p,
        repeat_penalty=1.1,
        top_k=top_k,
        stop=['</s>'],
        echo=False,
        seed=42,
    )

    # Return only the generated answer text
    return response["choices"][0]["text"].strip()

"""### Changing Temp Parameter (0.7 vs 0)"""

query= 'What is the protocol for managing sepsis in a critical care unit?'
temperature = 0.7
top_p = 0.95
top_k = 50
max_tokens = 1024
print(generate_llama_response(query, temperature, top_p, top_k, max_tokens))

"""#### temperature = 0"""

query= 'What is the protocol for managing sepsis in a critical care unit?'
temperature = 0.0
top_p = 0.95
top_k = 50
max_tokens = 1024
print(generate_llama_response(query, temperature, top_p, top_k, max_tokens))

"""#### Observation

Temp 0.7 (Superior): Generated comprehensive, nuanced clinical protocol with specific medical metrics, resulting in highly useful, human-like output due to greater token exploration.

Temp 0.0 (Inferior): Produced incomplete, truncated, generic content, exhibiting a stiff, deterministic style that lacked critical detail for decision-making.

### Changing top_p Parameter (0.95 vs 0.85)
"""

query= 'What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?'
temperature = 0.7
top_p = 0.95
top_k = 50
max_tokens = 1024
print(generate_llama_response(query, temperature, top_p, top_k, max_tokens))

"""#### top_p=0.85"""

query= 'What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?'
temperature = 0.7
top_p = 0.85
top_k = 50
max_tokens = 1024
print(generate_llama_response(query, temperature, top_p, top_k, max_tokens))

"""#### Observation

* Answer 2 ($\text{top_p} = 0.85$): Superior—The narrower range created more focused and relevant content, minimizing irrelevant variation.
* Answer 1 ($\text{top_p} = 0.95$): Inferior—The wider range led to more diverse but general content and less precise output.
* Conclusion: A slightly lower $\text{top_p}$ improved quality by demanding greater concentration on the most probable tokens.

### Changing top_k Parameter (50 vs 80)
"""

query= 'What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?'
temperature = 0.7
top_p = 0.95
top_k = 50
max_tokens = 1024
print(generate_llama_response(query, temperature, top_p, top_k, max_tokens))

"""#### top_k=80"""

query= 'What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?'
temperature = 0.7
top_p = 0.95
top_k = 80
max_tokens = 1024
print(generate_llama_response(query, temperature, top_p, top_k, max_tokens))

"""#### Observation

The comparison shows how increasing the $\text{top_k}$ value can influence the depth and specificity of the response.

* Answer 2 ($\text{top_k} = 80$): Superior. The wider $K$ allowed the model to access a broader vocabulary, resulting in deeper clinical detail and more actionable insights regarding specific treatments (Alopecia Areata, Traction Alopecia).
* Answer 1 ($\text{top_k} = 50$): Inferior. The narrower $K$ restricted the model, yielding a more general overview that listed causes and only briefly mentioned treatments.

* Conclusion: For this medical project, a higher $\text{top_k}$ (80) was more effective, providing the necessary level of clinical depth required for actionable results.

### Changing max_tokens Parameter (1024 vs 512)
"""

query= 'What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?'
temperature = 0.7
top_p = 0.95
top_k = 50
max_tokens = 1024
print(generate_llama_response(query, temperature, top_p, top_k, max_tokens))

"""#### max_token=512"""

query= 'What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?'
temperature = 0.7
top_p = 0.95
top_k = 50
max_tokens = 512
print(generate_llama_response(query, temperature, top_p, top_k, max_tokens))

"""#### Observation

The comparison clearly shows that increasing the $\text{Max_tokens}$ parameter directly translates to a more comprehensive and well-rounded response.

* Answer 1 ($\text{Max_tokens} = 1024$): Superior. Provided a comprehensive and detailed overview of brain injury treatment, including specific interventions and covering a wider range of recovery aspects (physical, cognitive, and emotional support).

* Answer 2 ($\text{Max_tokens} = 512$): Inferior. Was more concise, focusing only on key areas (initial care, medications, rehabilitation). While medically accurate, the answer was less detailed and omitted broader aspects of recovery.

* Conclusion: For complex topics like medical protocols, the larger $\text{Max_tokens}$ (1024) is preferred as it allows the model to fully elaborate and provide a more holistic and detailed answer.

### Basic vs top parameters
"""

query= 'What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?'
temperature = 0.7
top_p = 0.95
top_k = 50
max_tokens = 1024
print(generate_llama_response(query, temperature, top_p, top_k, max_tokens))

query= 'What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?'
temperature = 0.7
top_p = 0.85
top_k = 80
max_tokens = 1024
print(generate_llama_response(query, temperature, top_p, top_k, max_tokens))

"""#### Observation

* Modified Parameters (Answer 2) were Superior: Produced a holistic and structured response that covered both immediate care and long-term recovery (e.g., nutrition, physical therapy).

* Default Parameters (Answer 1) were Inferior: Focused too narrowly on immediate emergency steps (e.g., severity assessment), lacking a comprehensive follow-up plan.

* Conclusion: Modification successfully shifted the model from a simple emergency protocol to a complete, structured guide covering the full recovery process.

## **Loading the data**
"""

# uncomment and run the below code snippets if the dataset is present in the Google Drive
from google.colab import drive
drive.mount('/content/drive')

pdf_file = "/content/drive/My Drive/Colab Notebooks/NLP_Project/medical_diagnosis_manual.pdf"

pdf_loader = PyPDFLoader(pdf_file)

merck = pdf_loader.load()

from langchain.schema import Document # Import the Document class

phrase_to_remove = "This file is meant for personal use by rajasekar.t7@gmail.com only."
cleaned_docs = []

for doc in merck:
    # Remove the specific contamination phrase and clean up whitespace
    cleaned_content = doc.page_content.replace(phrase_to_remove, "").strip()

    # Create a new Document object with the cleaned content and original metadata
    cleaned_doc = Document(page_content=cleaned_content, metadata=doc.metadata)
    cleaned_docs.append(cleaned_doc)

merck=cleaned_docs

len(merck)

"""## **Retrieval Augmented Generation (RAG) Process**

### **Implementing RAG**

#### Chunking documents
"""

text_splitter = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
    encoding_name='cl100k_base',
    chunk_size=512,
    chunk_overlap=16,
    is_separator_regex=False,
)

"""The given code initializes a **RecursiveCharacterTextSplitter** to split the text into manageable chunks for embedding and retrieval. Here's a breakdown:

- `RecursiveCharacterTextSplitter.from_tiktoken_encoder(...)`: Uses **TikToken encoding** to properly handle token-based splitting.
- `encoding_name='cl100k_base'`: Specifies the **TikToken encoding** (used by OpenAI models like GPT-4 and GPT-3.5).
- `chunk_size=512`: Each text chunk will have a maximum of **512 tokens**.
- `chunk_overlap=16`: Ensures **overlapping** of 16 tokens between consecutive chunks to preserve context.

This approach ensures that text is split **intelligently** while maintaining **semantic meaning** for better retrieval and embeddings.
"""

document_chunks = pdf_loader.load_and_split(text_splitter)

len(document_chunks)

"""Let's take a look at consecutive chunks from the document."""

i = 5
print(document_chunks[i])

print(document_chunks[i+1])

"""As we can see there is some overlap between the chunks. This improves the coherence and relevance of retrieved results, as the model can better understand the relationship between adjacent parts of the document. It also helps in maintaining the flow of ideas and ensuring that critical context is available when generating answers, leading to more accurate and contextually consistent outputs.

#### Choosing an embedding model

A good general-purpose embedding model is [`gte-large`](https://huggingface.co/thenlper/gte-large). The main reason for choosing this model is because of its embedding vector size, which is 512, the same as our token size in chunking.
"""

embedding_model = SentenceTransformerEmbeddings(model_name='thenlper/gte-large')

# Generating embedding for the first document chunk
embedding_1 = embedding_model.embed_query(document_chunks[0].page_content)
# Generating embedding for the second document chunk
embedding_2 = embedding_model.embed_query(document_chunks[1].page_content)

#Checking if both are of the same size
print("Dimension of the embedding vector ",len(embedding_1))
len(embedding_1)==len(embedding_2)

"""Now that we have chunked the raw input, **we can present these chunks to an embedding model and then store the generated embeddings into a vector database.**
  - We generate a vector for each chunk and save this chunk along with the vector representation in a specialized database.

#### Creating a Vector Database

While embeddings solve for retrieval of appropriate context given a query, a more efficient application of vectorization is to transform raw data into smaller chunks before feeding it to an embedding model. There are two important reasons why this is needed:

- Embedding models are themselves Transformer models and hence have input length constraints. Any text that is longer than the maximum input length allowed by the embedding model is usually truncated.
- Slicing the data into chunks facilitates fine-grained control of the specific information that can be injected as context. This helps the model focus only on the information most relevant to the query.
"""

import os
out_dir = 'merck_db'

if not os.path.exists(out_dir):
  os.makedirs(out_dir)

vectorstore = Chroma.from_documents( #creating a Chroma vector store from a set of document chunks.
    document_chunks, #creating a list of text chunks that will be converted into embeddings..
    embedding_model, #model responsible for embedding the document chunks into vector representations
    persist_directory=out_dir #name of the collection in the Chroma database
)

vectorstore = Chroma(persist_directory=out_dir,embedding_function=embedding_model)

print(vectorstore.embeddings)

print(vectorstore.similarity_search("Alopecia Areata ",k=3))

"""#### Retrieval

The user input is converted to a vector representation using the same model that was used for the context chunks. Then a similarity search is executed against the vectorized chunks in the vector database. Top-$k$ chunks from the search results in this step are then stuffed into the prompt as the context and the LLM is instructed to answer the user query using only the context.

We will now create a retriever that can query an input text and retrieve the top$-k$ documents that are most relevant from the vector store.

- Under the hood, a similarity score is computed between the embedded query and all the chunks in the database
- The top $k$ chunks with the highest similarity scores are then returned.
"""

retriever = vectorstore.as_retriever( #Converting the Chroma vector store into a retriever for querying.
    search_type='similarity', #Specifying that retrieval is based on cosine similarity
    search_kwargs={'k': 3} #Retrieving the top 3 most similar documents for a given query.
)

user_input = 'What are the symptoms of migraine?'
rel_docs = retriever.get_relevant_documents(user_input)
print(rel_docs)

"""### **System and User Prompt Template**"""

# System message instructing the LLM to only answer using Merck Manual 19th Edition
qna_system_message = """
You are a helpful assistant trained to answer questions based only on the Merck Manual of Medical Diagnosis and Therapy, Nineteenth Edition.
Use the context provided to find accurate and reliable answers.
If the answer is not found in the context, reply with "I don't know".
Do not mention the context or the Merck Manual in your final answer.
"""

# Template for formatting the user's input with context from the Merck Manual, 19th Edition and the actual medical question.
qna_user_message_template = """
###Context
The following excerpts are from the Merck Manual of Medical Diagnosis and Therapy, Nineteenth Edition:
{context}

###Question
{question}
"""

"""#### Response Function"""

def generate_rag_response(user_input,ret,k=3,max_tokens=128,temperature=0,top_p=0.95,top_k=50):
    global qna_system_message,qna_user_message_template
    # Retrieve relevant document chunks
    relevant_document_chunks = ret.get_relevant_documents(query=user_input,k=k)
    context_list = [d.page_content for d in relevant_document_chunks]

    # Combine document chunks into a single context
    context_for_query = ". ".join(context_list)

    user_message = qna_user_message_template.replace('{context}', context_for_query)
    user_message = user_message.replace('{question}', user_input)

    prompt = qna_system_message + '\n' + user_message

    # Generate the response
    try:
        response = llm(
                  prompt=prompt,
                  max_tokens=max_tokens,
                  temperature=temperature,
                  top_p=top_p,
                  top_k=top_k
                  )

        # Extract and print the model's response
        response = response['choices'][0]['text'].strip()
    except Exception as e:
        response = f'Sorry, I encountered the following error: \n {e}'

    return response

"""### **Q&A with RAG**

##### Basic Parameter
"""

user_input1 = 'What is the protocol for managing sepsis in a critical care unit?'
print(generate_rag_response(user_input1,retriever))

"""##### Removing chunk overlap"""

# Initializing a RecursiveCharacterTextSplitter to split the text into manageable chunks for embedding and retrieval
text_splitter1 = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
    encoding_name='cl100k_base',
    chunk_size=512,
    chunk_overlap= 0,
    is_separator_regex=False,
)

#loading the PDF document, extracting its text, and splitting it into smaller chunks
document_chunks1 = pdf_loader.load_and_split(text_splitter1)

len(document_chunks1)

# Generating embedding for the first document chunk
embedding_1 = embedding_model.embed_query(document_chunks1[0].page_content)
# Generating embedding for the second document chunk
embedding_2 = embedding_model.embed_query(document_chunks1[1].page_content)

vectorstore1 = Chroma.from_documents( #creating a Chroma vector store from a set of document chunks.
    document_chunks1, #creating a list of text chunks that will be converted into embeddings..
    embedding_model, #model responsible for embedding the document chunks into vector representations
    persist_directory=out_dir #name of the collection in the Chroma database
)

vectorstore1 = Chroma(persist_directory=out_dir,embedding_function=embedding_model)

print(vectorstore1.embeddings)

retriever1 = vectorstore1.as_retriever( #Converting the Chroma vector store into a retriever for querying.
    search_type='similarity', #Specifying that retrieval is based on cosine similarity
    search_kwargs={'k': 3} #Retrieving the top 3 most similar documents for a given query.
)

user_input1 = 'What is the protocol for managing sepsis in a critical care unit?'
print(generate_rag_response(user_input1,retriever1))

"""##### Observation

Removing chunk overlap did not change the answers in this case, probably because the relavant information for the question was already contained within a single chunk.

Removing chunk overlap might affect the answer if the question required information that spanned across multiple chunks from different parts of the text.

##### Basic Parameter
"""

user_input2 = 'What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?'
print(generate_rag_response(user_input2,retriever))

"""##### Fine Tuning - Retreiver Parameters"""

retriever2 = vectorstore.as_retriever( #Converting the Chroma vector store into a retriever for querying.
    search_type='similarity', #Specifying that retrieval is based on cosine similarity
    search_kwargs={'k': 2} #Retrieving the top 2 most similar documents for a given query.
)

user_input2 = 'What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?'
print(generate_rag_response(user_input2,retriever2))

"""##### Observation

Answer 1, with k=3, is slightly more detailed and includes examples of cases (like when surgery is impossible).

Answer 2, with k=2, is slightly shorter and cuts off earlier, suggesting that retrieving more chunks (k=3) provided additional helpful context for a more complete answer.

##### Basic Parameter
"""

user_input3 = 'What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?'
print(generate_rag_response(user_input3, retriever))

"""##### Fine tuning temp=0.7"""

user_input3 = 'What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?'
print(generate_rag_response(user_input3, retriever, temperature=0.7))

"""##### Observation

Answer 1, with temperature = 0, is more precise and structured.

Answer 2, with temperature = 0.7, introduces a bit more variability, with slight changes in wording, reflecting the increased randomness from the higher temperature.

##### Basic Parameter
"""

user_input4 = 'What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?'
print(generate_rag_response(user_input4,retriever))

"""##### top_p=0.8"""

user_input4 = 'What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?'
print(generate_rag_response(user_input4, retriever, top_p=0.8))

"""##### Observation

Answer 1 with Top_p = 0.95 means the model will consider the top 95% probability mass of the next token and select from that pool. This makes the answer generated more focused, coherent responses because it prioritizes more likely words and phrases.

Answer 2 with Top_p = 0.8 means the model restricts the token selection to only the top 80% of the probability distribution, including less likely but more diverse options.

Thus, in Answer 1, the model focuses more on the main facts (like supportive care and rehab) without adding unnecessary or unrelated details. In Answer 2, the model explores a wider range of possibilities, leading to additional information about severe cases, surgery, and treatment phases.

##### Basic Parameter
"""

user_input5 = 'What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?'
print(generate_rag_response(user_input5,retriever))

"""##### top_k=25"""

user_input5 = 'What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?'
print(generate_rag_response(user_input5,retriever, top_k=25))

"""##### Observation

More or less it is the same output there is no much difference

## **Output Evaluation**

### Rating system
"""

groundedness_rater_system_message = """

You will be presented a ###Question, ###Context used by the AI system and AI generated ###Answer.

Your task is to judge the extent to which the ###Answer is derived from ###Context.

Rate it 1 - if The ###Answer is not derived from the ###Context at all
Rate it 2 - if The ###Answer is derived from the ###Context only to a limited extent
Rate it 3 - if The ###Answer is derived from ###Context to a good extent
Rate it 4 - if The ###Answer is derived from ###Context mostly
Rate it 5 - if The ###Answer is is derived from ###Context completely

Please note: Make sure you give a single overall rating in the range of 1 to 5 along with an overall explanation.

"""

relevance_rater_system_message = """

You will be presented with a ###Question, the ###Context used by the AI system to generate a response, and the AI-generated ###Answer.

Your task is to judge the extent to which the ###Answer is relevant to the ###Question, considering whether it directly addresses the key aspects of the ###Question based on the provided ###Context.

Rate the relevance as follows:
- Rate 1 – The ###Answer is not relevant to the ###Question at all.
- Rate 2 – The ###Answer is only slightly relevant to the **###Question**, missing key aspects.
- Rate 3 – The ###Answer is moderately relevant, addressing some parts of the **###Question** but leaving out important details.
- Rate 4 – The ###Answer is mostly relevant, covering key aspects but with minor gaps.
- Rate 5 – The ###Answer is fully relevant, directly answering all important aspects of the **###Question** with appropriate details from the **###Context**.

Note: Provide a single overall rating in the range of 1 to 5, along with a brief explanation of why you assigned that score.
"""

user_message_template = """
###Question
{question}

###Context
{context}

###Answer
{answer}
"""

"""### Evaluation function"""

def generate_ground_relevance_response(user_input,ret,k=3,max_tokens=128,temperature=0,top_p=0.95,top_k=50):
    global qna_system_message,qna_user_message_template
    # Retrieve relevant document chunks
    relevant_document_chunks = ret.get_relevant_documents(query=user_input,k=k)
    context_list = [d.page_content for d in relevant_document_chunks]
    context_for_query = ". ".join(context_list)

    user_message = qna_user_message_template.replace('{context}', context_for_query)
    user_message = user_message.replace('{question}', user_input)

    prompt = qna_system_message + '\n' + user_message

    # Print the prompt to inspect its length
    print("--- Generated Prompt ---")
    print(prompt)
    print("--- End of Generated Prompt ---")


    # Generate the response
    try:
        response = llm(
                  prompt=prompt,
                  max_tokens=max_tokens,
                  temperature=temperature,
                  top_p=top_p,
                  top_k=top_k
                  )

        # Extract and print the model's response
        answer = response['choices'][0]['text'].strip()
    except Exception as e:
        answer = f'Sorry, I encountered the following error: \n {e}'

    # Combine user_prompt and system_message to create the prompt for groundedness and relevance raters
    groundedness_prompt = f"""[INST]{groundedness_rater_system_message}\n
                {'user'}: {user_message_template.format(context=context_for_query, question=user_input, answer=answer)}
                [/INST]"""

    relevance_prompt = f"""[INST]{relevance_rater_system_message}\n
                {'user'}: {user_message_template.format(context=context_for_query, question=user_input, answer=answer)}
                [/INST]"""

    response_1 = llm(
            prompt=groundedness_prompt,
            max_tokens=max_tokens,
            temperature=temperature,
            top_p=top_p,
            top_k=top_k,
            stop=['INST'],
            echo=False
            )

    response_2 = llm(
            prompt=relevance_prompt,
            max_tokens=max_tokens,
            temperature=temperature,
            top_p=top_p,
            top_k=top_k,
            stop=['INST'],
            echo=False
            )

    return response_1['choices'][0]['text'],response_2['choices'][0]['text']

"""### Evaluation

#### Query1
"""

user_input1 = 'What is the protocol for managing sepsis in a critical care unit?'
ground,rel = generate_ground_relevance_response(user_input1,retriever2,k=3,max_tokens=350)

print(ground,end="\n\n")
print(rel)

"""#### Observation

Rating is 5 -- grounding and relevance means the answer is fully substantiated by the context and is maximally pertinent to the query.

#### Query2
"""

user_input2 = 'What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?'
ground,rel = generate_ground_relevance_response(user_input2,retriever2,k=3,max_tokens=350)


print(ground,end="\n\n")
print(rel)

"""#### Observation

Rating is 5 -- grounding and relevance means the answer is fully substantiated by the context and is maximally pertinent to the query.

#### Query3
"""

user_input3 = 'What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?'
ground,rel = generate_ground_relevance_response(user_input3,retriever2,k=3,max_tokens=350)



print(ground,end="\n\n")
print(rel)

"""#### Observation

Rating is 5 -- grounding and relevance means the answer is fully substantiated by the context and is maximally pertinent to the query.

#### Query4
"""

user_input4 = 'What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?'
ground,rel = generate_ground_relevance_response(user_input4,retriever2,k=3,max_tokens=350)


print(ground,end="\n\n")
print(rel)

"""#### Observation

Rating is 5 -- grounding and relevance means the answer is fully substantiated by the context and is maximally pertinent to the query.

#### Query5
"""

user_input5 = 'What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?'
ground,rel = generate_ground_relevance_response(user_input5,retriever2,k=3,max_tokens=350)


print(ground,end="\n\n")
print(rel)

"""#### Observation

Rating is 5 -- grounding and relevance means the answer is fully substantiated by the context and is maximally pertinent to the query.

# **Conclusion**

**Business Benefits (Insights & Value)**

* High Trust & Reliability: RAG-based answers are context-specific and highly reliable, directly enhancing customer satisfaction and trust in medical applications.

* Superior User Experience (UX): The model provides personalized, relevant, and accurate responses, leading to a significantly improved user experience.

* Cost Efficiency: Automating medical Q&A dramatically reduces the necessity for human consultations, leading to substantial cost savings in telemedicine and healthcare support services.

**Strategic Recommendations (Future Action)**

* Mandatory Continuous Fine-tuning: The model requires ongoing updates and fine-tuning to reflect the latest medical guidelines and research (ensuring information remains current).

* Develop Specialized Models: Create dedicated models tailored to individual medical specialties (e.g., orthopedics, oncology) to maximize accuracy and relevance within specific domains.
"""